#pragma once

#include <glcore/handle.hpp>

#include <filesystem>
#include <span>

// Texture and sampler creation, for the texturing chapters (14 onward).
//
// Textures are loaded with gli, which reads KTX and DDS -- GPU-ready container
// formats -- rather than decoding PNG or JPEG at runtime. The consequence worth
// internalizing: the internal format lives in the *file*, so whether data is
// sRGB or linear, and whether it is block-compressed, is decided when the asset
// is authored. Convert source images with tools/png_to_ktx.py.
//
// Textures built in code (which several of the texturing chapters do) go
// through makeTexture2D and need no file at all.

namespace glc {

struct Texture2DOptions {
	/// Build a mip chain when the source carries only a base level. Ignored for
	/// files that already ship a mip chain, and for compressed formats, whose
	/// mips cannot be generated by the driver.
	bool generateMipmaps = true;
};

/// Loads a KTX or DDS 2D texture.
///
/// Throws if the file is missing, is not a format gli reads, or is not 2D --
/// the error names tools/png_to_ktx.py, since "I pointed it at a PNG" is the
/// overwhelmingly likely mistake.
[[nodiscard]] Texture loadTexture2D(const std::filesystem::path& path,
                                    const Texture2DOptions& options = {});

/// Uploads pixels already in memory. This is the path for procedurally
/// generated textures, and the escape hatch when you have bytes from anywhere.
///
/// `internalFormat` is what GL stores (GL_RGB8, GL_SRGB8, ...); `format` and
/// `type` describe the bytes you are handing over (GL_RGB, GL_UNSIGNED_BYTE).
[[nodiscard]] Texture makeTexture2D(GLsizei width, GLsizei height, GLenum internalFormat,
                                    GLenum format, GLenum type, const void* pixels,
                                    const Texture2DOptions& options = {});

/// One image of an explicitly supplied mip chain.
struct MipLevel {
	GLsizei width;
	GLsizei height;
	const void* pixels;
};

/// Uploads a mip chain whose levels are given rather than generated.
///
/// glGenerateMipmap covers the usual case -- smaller versions of one image --
/// and this covers the case where the levels are not versions of each other at
/// all. Tutorial 15 builds one whose every level is a different flat colour, so
/// that the boundary between mipmaps is visible on screen; a chain loaded from
/// a file that gli cannot read would come through here too.
///
/// `levels[0]` is the base image and each entry should be half the size of the
/// one before, down to 1x1, since that is what GL considers a complete chain.
/// GL_TEXTURE_MAX_LEVEL is set to the last index supplied, so a partial chain
/// is complete as far as it goes.
///
/// There are no options: a caller supplying its own levels is not asking for
/// generated ones.
///
/// \throws std::runtime_error if `levels` is empty or any extent is not
/// positive.
[[nodiscard]] Texture makeTexture2D(std::span<const MipLevel> levels, GLenum internalFormat,
                                    GLenum format, GLenum type);

/// Uploads a one-dimensional image -- an array of texels indexed by a single
/// normalized coordinate.
///
/// Tutorial 14 opens with one of these holding a look-up table, which is the
/// clearest demonstration that a texture need not be a picture: nothing in it
/// is a colour, and it is never looked at.
///
/// There are no options because a look-up table wants none of them: it is one
/// level with no mip chain (set here, so the texture is complete under any
/// filter), and everything else about how it is read belongs to the sampler.
[[nodiscard]] Texture makeTexture1D(GLsizei width, GLenum internalFormat, GLenum format,
                                    GLenum type, const void* pixels);

struct SamplerOptions {
	GLenum minFilter = GL_LINEAR_MIPMAP_LINEAR;
	GLenum magFilter = GL_LINEAR;
	GLenum wrapS = GL_REPEAT;
	GLenum wrapT = GL_REPEAT;

	/// 1.0 disables anisotropic filtering. Values above the driver's limit are
	/// clamped rather than rejected.
	float maxAnisotropy = 1.0F;
};

/// Sampler objects (GL 3.3) keep filtering separate from the texture, which is
/// exactly the split Tutorial 15 (Many Images) is about.
[[nodiscard]] Sampler makeSampler(const SamplerOptions& options = {});

/// Largest anisotropy this driver supports, or 1.0 if the extension is absent.
[[nodiscard]] float maxSupportedAnisotropy();

/// Binds `texture` and `sampler` to a texture unit together.
void bindTextureUnit(GLuint unit, const Texture& texture, const Sampler& sampler,
                     GLenum target = GL_TEXTURE_2D);

} // namespace glc
