#pragma once

#include <glcore/handle.hpp>

#include <filesystem>

// Texture and sampler creation, for the texturing chapters (14 onward).
//
// Textures are loaded with gli, which reads KTX and DDS -- GPU-ready container
// formats -- rather than decoding PNG or JPEG at runtime. The consequence worth
// internalizing: the internal format lives in the *file*, so whether data is
// sRGB or linear, and whether it is block-compressed, is decided when the asset
// is authored. Convert source images with tools/png_to_ktx.py.
//
// Textures built in code (which several of the texturing chapters do) go
// through makeTexture2D and need no file at all.

namespace glc {

struct Texture2DOptions {
	/// Build a mip chain when the source carries only a base level. Ignored for
	/// files that already ship a mip chain, and for compressed formats, whose
	/// mips cannot be generated by the driver.
	bool generateMipmaps = true;
};

/// Loads a KTX or DDS 2D texture.
///
/// Throws if the file is missing, is not a format gli reads, or is not 2D --
/// the error names tools/png_to_ktx.py, since "I pointed it at a PNG" is the
/// overwhelmingly likely mistake.
[[nodiscard]] Texture loadTexture2D(const std::filesystem::path& path,
                                    const Texture2DOptions& options = {});

/// Uploads pixels already in memory. This is the path for procedurally
/// generated textures, and the escape hatch when you have bytes from anywhere.
///
/// `internalFormat` is what GL stores (GL_RGB8, GL_SRGB8, ...); `format` and
/// `type` describe the bytes you are handing over (GL_RGB, GL_UNSIGNED_BYTE).
[[nodiscard]] Texture makeTexture2D(GLsizei width, GLsizei height, GLenum internalFormat,
                                    GLenum format, GLenum type, const void* pixels,
                                    const Texture2DOptions& options = {});

struct SamplerOptions {
	GLenum minFilter = GL_LINEAR_MIPMAP_LINEAR;
	GLenum magFilter = GL_LINEAR;
	GLenum wrapS = GL_REPEAT;
	GLenum wrapT = GL_REPEAT;

	/// 1.0 disables anisotropic filtering. Values above the driver's limit are
	/// clamped rather than rejected.
	float maxAnisotropy = 1.0F;
};

/// Sampler objects (GL 3.3) keep filtering separate from the texture, which is
/// exactly the split Tutorial 15 (Many Images) is about.
[[nodiscard]] Sampler makeSampler(const SamplerOptions& options = {});

/// Largest anisotropy this driver supports, or 1.0 if the extension is absent.
[[nodiscard]] float maxSupportedAnisotropy();

/// Binds `texture` and `sampler` to a texture unit together.
void bindTextureUnit(GLuint unit, const Texture& texture, const Sampler& sampler,
                     GLenum target = GL_TEXTURE_2D);

} // namespace glc
